docker-compose-yaml: 'docker-compose.frontend.yml'

project: druxtjs-org-demo-commerce

environments:
  staging/frontend:
    routes:
      - app:
          - staging.commerce.demo.druxtjs.org
      - storybook:
          - storybook.staging.commerce.demo.druxtjs.org
  production/frontend:
    routes:
      - app:
          - commerce.demo.druxtjs.org
      - storybook:
          - storybook.commerce.demo.druxtjs.org
