version: '2.3'

services:
  app:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: .docker/Dockerfile.app
      args:
        OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
    labels:
      lagoon.type: node
      lando.type: node
    environment:
      LAGOON_LOCALDEV_HTTP_PORT: 3000
      LAGOON_ROUTE: http://druxtjs-org-demo-commerce.docker.amazee.io

  storybook:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: .docker/Dockerfile.storybook
      args:
        OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
    labels:
      lagoon.type: node
      lando.type: node
    environment:
      LAGOON_LOCALDEV_HTTP_PORT: 3000
      LAGOON_ROUTE: http://storybook-druxtjs-org-demo-commerce.docker.amazee.io

networks:
  amazeeio-network:
    external: true
